# Generated by Django 4.1.2 on 2022-10-20 03:56

from django.db import migrations, models
import earthquakes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosestEarthquake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                (
                    "search_range",
                    models.JSONField(
                        default=earthquakes.models.search_default,
                        unique=True,
                        verbose_name="search_range",
                    ),
                ),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("magnitude", models.FloatField(default=0.0)),
                ("city", models.ManyToManyField(to="cities.city")),
            ],
        ),
    ]
